/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000 # Hz
        
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
          
      arm_controller:
        type: position_controllers/JointGroupPositionController

  arm_controller:
    ros__parameters:
      joints:
        - shoulder_pan_joint
        - shoulder_lift_joint
        - elbow_joint 
        - wrist_1_joint
        - wrist_2_joint
        - wrist_3_joint